# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:      pretty
baseurl: 	    	/2024sp-GenAI-Risk-Benefits/
url:            https://qiyanjun.github.io/

# Setup
title:            	"2024 Spring UVA CS - GenAI-Risk-Benefits"
tagline:          	"2024 Spring"
description:        "Graduate Level Seminar"
future: 			true

author:
  name:           'Dr. Yanjun Qi'
  url:            https://www.yanjunqi.org/


remote_theme: mmistakes/minimal-mistakes@4.24.0

collections:
  contents:
    sort_by: LOrder
    output: true

plugins: 
  - jekyll-include-cache
